### ISSUE TITLE
Can you add a license?

### ISSUE THREAD

**Issue by erjel** [yanchaoz/SegNeuron#1]
Hi @yanchaoz,

thank you for your [MICCAI 2024 contribution](https://link.springer.com/chapter/10.1007/978-3-031-72111-3_55). Very nice idea and paper! ❤️ 

Also thank you for sharing your code, model, and datasets. 👍

I would like to run some experiments with the code and check whether I can reproduce your results. Can you please [add a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to the repository? Unfortunately, I am [not allowed](https://choosealicense.com/no-permission/) to use your code for any experiments without a license.

Thank you in advance!

Best wishes,
Eric

**Comment by yanchaoz** [comment]
Hi Eric,

Thank you for your interest in our MICCAI 2024 work! 

I’ve added the MIT license to the repository, so you should now be able to run experiments and reproduce the results without any concerns. Please feel free to reach out if you have any further questions.

Best regards,
Yanchao

**Comment by erjel** [comment]
Thank you a lot!
