### ISSUE TITLE
Can you add a requirements.txt?

### ISSUE THREAD

**Issue by Mariosz2** [yanchaoz/SegNeuron#2]
Hi @yanchaoz, 

I am very interested in your paper MICCAI 2024, it is an outstanding piece of work, thank you for sharing the code and data.

Now I want to reproduce the code of your paper, but the version of the experimental environment and package is not certain. Could you please add the requirements.txt or docker of the experimental environment？

**Comment by yanchaoz** [comment]
Hi  @Mariosz2,

Thank you for your interest! I’ve added the requirements.txt to the repository. 

Best regards,
Yanchao

**Comment by Mariosz2** [comment]
Thank you very much!

**Comment by Mariosz2** [comment]
Hello @yanchaoz,

I tried the requirements.txt you added for environment configuration, but the process didn't go very well. On the one hand, some libraries in the code such as em_segLib are not described in requirements, and on the other hand, there are conflicting library versions in requirements.

Is it convenient to make a docker environment? I am very grateful if it is possible, and your method can be reproduced more conveniently and simply.

Best regards,
Shushen
