### ISSUE TITLE
Is valid_provider.py missing?

### ISSUE THREAD

**Issue by Mariosz2** [yanchaoz/SegNeuron#3]
Hi @yanchaoz ,

There was a problem when I tried to run the code. Line 20 of `pretrain/pretrain.py` is `from valid_provider import Provider_valid`, but there is no `valid_provider.py` file in the sibling directory. The `valid_provider` third-party library is also not found.

Is the `valid_provider.py` file missing?

Best regards,
Shushen

**Comment by yanchaoz** [comment]
Hi~

**Comment by yanchaoz** [comment]
Hi~

**Comment by yanchaoz** [comment]
Hi Shushen,

In fact, valid_provider is not required during the pretraining. You can directly delete the relevant usage. 

This was an oversight during the code organization process. I have already corrected it in the codebase. 

Best regards,
Yanchao
