### ISSUE TITLE
Questions about the datasets

### ISSUE THREAD

**Issue by Mariosz2** [yanchaoz/SegNeuron#4]
Hi @yanchaoz ,

I downloaded and checked the dataset you provided, including the labeled and valid sections, but there are only 10 folders in the labeled section, so are there only 10 kinds of datasets? Your paper says "Dataset 1∼13 is used for model development, and 14∼16 for evaluation." And I can't match the dataset name with the code or the paper. `pretrain_provider.py` contains the names of 13 datasets.

I have another request. If possible, could you give me your email address to facilitate communication with you?

Best regards,
Shushen

**Comment by Mariosz2** [comment]
In line 44 of `Pretrain/pretrain_provider.py`, if `k = random.randint(0, len(self.dataset))`, should it be changed to `k = random.randint(0, len(self.dataset)-1)`?

**Comment by yanchaoz** [comment]
> In line 44 of `Pretrain/pretrain_provider.py`, if `k = random.randint(0, len(self.dataset))`, should it be changed to `k = random.randint(0, len(self.dataset)-1)`?

That's right! Thanks for pointing that out.

**Comment by yanchaoz** [comment]
> Hi @yanchaoz ,
> 
> I downloaded and checked the dataset you provided, including the labeled and valid sections, but there are only 10 folders in the labeled section, so are there only 10 kinds of datasets? Your paper says "Dataset 1∼13 is used for model development, and 14∼16 for evaluation." And I can't match the dataset name with the code or the paper. `pretrain_provider.py` contains the names of 13 datasets.
> 
> I have another request. If possible, could you give me your email address to facilitate communication with you?
> 
> Best regards, Shushen

Sure. My email address is zhangyanchao2021@ia.ac.cn. Please feel free to reach out to me at any time for more discussions.
